### ISSUE TITLE
Warnings for tests with upcoming arules_1.6-6

### ISSUE THREAD

**Issue by mhahsler** [neuroimaginador/fcaR#15]
Testing with the new version of rules (arules_1.6-6) produces the following warning:

```
 test-implication_set.R:97: warning: fcaR exports implications to arules
minimum support or confidence not available in info(x). Using uncorrected std_lift instead.
```

The issue is that the new measure `stdLift` needs information on the used thresholds for mining the rules. These are stored in `info(x)$support` and `info(x)$confidence`, but are missing in your code. More measures in the future might need such information as well.

The options are to 

- add the information to your rules object or to 
- specify only a select set of interestMeasures when you use `fc$implications$to_arules(quality = TRUE)`.

Regards,
-Michael

**Comment by neuroimaginador** [comment]
Dear Michael,

Thank you very much for your feedback, I will try both options you mention and hope it fixes the issue. It affects a key point in this package, the interface with _your_ `arules` package.

Best wishes,
Domingo

**Comment by neuroimaginador** [comment]
Last commit solved the issue. Thank you very much!
