### ISSUE TITLE
closure() creates ImplicationSet which cannot be converted using to_arules()

### ISSUE THREAD

**Issue by pattisot** [neuroimaginador/fcaR#17]
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem
In fcaR v1.0.3, the ImplicationSet created by closure() sets private$I to NULL, so that the set cannot be converted using to_arules(). I am using RStudio Version 1.2.5033.

```r
library("fcaR")
library("arules")
fc_planets <- FormalContext$new(planets)
fc_planets$find_implications()
S <- SparseSet$new(attributes = fc_planets$attributes)
fc_planets$implications$closure(S,reduce=TRUE,verbose=TRUE)$implications$to_arules(quality=TRUE)
```

**Comment by neuroimaginador** [comment]
Hello,

Certainly, there is a bug when the `closure()` method is called with `reduce = TRUE`. The solution is to add a single line, that I will introduce in next commit.

Thank you!!
